language: php
dist: xenial
php:
  - 7.2

env:
  - APP_STATUS=development

services:
  - redis
  - mysql5.7
  - nginx

branches:
  only:
  - master
  - travis

before_install:


before_script:
  - git clone https://github.com/gopeak/hornet-framework.git
  - git clone https://github.com/phpredis/phpredis.git
  - cd phpredis/
  - phpize
  - ./configure
  - make
  - make install

  - mysql -e -utravis "create database IF NOT EXISTS masterlab_ci  character set utf8mb4 collate utf8mb4_unicode_ci"
  - mysql -e -utravis "use masterlab_ci;source $TRAVIS_BUILD_DIR/masterlab.sql" 

script:

  - cd $TRAVIS_BUILD_DIR/gopeak/masterlab
  - composer update
  - php test_mysql.php
  - cd app/test

notifications:
  email:
    - 121642038@qq.com

addons:
  ssh_known_hosts: 47.244.62.11
  hosts:
    - travis.test
    - masterlab.ci

cache:
  directories:
  - vendor