language: php

dist: trusty
sudo: false

php:
  - 7.2

env:
  - APP_STATUS=travis

services:
  - redis-server
  - mysql
  - nginx
  - mongodb

matrix:
  fast_finish: true

branches:
  only:
  - master
  - travis

cache:
  apt: true
  directories:
    - $HOME/.composer/cache/files

before_install:
  
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('Masterlab123') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -pMasterlab123
  - sudo service mysql restart
  - sudo mysql -e "create database IF NOT EXISTS masterlab_ci;" -uroot -pMasterlab123
  - sudo mysql -e "SET sql_mode = 'IGNORE_SPACE,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';use masterlab_ci;source $TRAVIS_BUILD_DIR/masterlab.sql;" -uroot -pMasterlab123 
  
  - sudo echo "[mysqld]" >> ~travis/.my.cnf
  - sudo echo 'sql-mode="IGNORE_SPACE,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTIO"' >> ~travis/.my.cnf
  - sudo service mysql restart
  - cat ~travis/.my.cnf

before_script:
  - git clone https://github.com/phpredis/phpredis.git
  - cd phpredis/
  - phpize
  - ./configure
  - make
  - make install
  - phpenv config-add $TRAVIS_BUILD_DIR/php.ini
  - git clone https://github.com/gopeak/hornet-framework.git /home/travis/build/gopeak/hornet-framework

script:
  - cd $TRAVIS_BUILD_DIR
  - echo $TRAVIS_BUILD_DIR
  - git checkout  travis
  - git pull origin travis
  - cp -f  env.ini-travis   env.ini
  - composer update
  - ls
  - chmod +x /home/travis/build/gopeak/masterlab/travis/install-nginx.sh
  - /home/travis/build/gopeak/masterlab/travis/install-nginx.sh

  #- cat /home/travis/build/gopeak/masterlab/travis/nginx/nginx.conf
 # - curl -vsf 'http://masterlab.dev:8080/test_mysql.php' &> /dev/stdout
  - curl -vsf  "http://travis.test:8888/framework/feature/getPhpIni?data_type=json" &> /dev/stdout
  - cat /tmp/error.log

  - php test_mysql.php
  - cd app/test
  #- phpunit  #--bootstrap ./bootstrap.php requirement/TestEnv.php
#  - cat /tmp/error.log

notifications:
  email:
    - 121642038@qq.com

addons:
  #ssh_known_hosts: 47.244.62.11
  hosts:
    - travis.test
    - masterlab.dev
  apt:
      sources:
        - mysql-5.7-trusty
      packages:
        - mysql-server
        - mysql-client
        - nginx
        - realpath
