language: php
dist: xenial
php:
  - 7.2

env:
  - APP_STATUS=development

services:
  - redis
  - mysql5.7
  - nginx

before_script:
  - cd ../
  - git clone --depth=50 git@github.com:gopeak/hornet-framework.git
  - composer install
  - composer update

script:
  - cd app/test
  - phpunit

notifications:
  email:
    - 121642038@qq.com

addons:
  ssh_known_hosts: 47.244.62.11